version: '2'
services:
  cloudflare-ddns-smart-hub:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=2pMHLxz4sc7PLOtALJmIzQyA85tBz4a1fLoCSyBT
      - ZONE=smart-hub.pw
      - PROXIED=false
